# ──────────────────────────────────────────────────────────────────────────────
# render-pdf.R — PDF backend for fr_render()
#
# Thin wrapper: generates .tex via render_latex(), compiles with XeLaTeX.
# Uses tinytex::xelatex() when available (auto-installs missing LaTeX
# packages), falls back to raw system2() otherwise.
# ──────────────────────────────────────────────────────────────────────────────

# ── Exported helpers ─────────────────────────────────────────────────────────

#' List Required LaTeX Packages
#'
#' Returns the CTAN package names that arframe's PDF backend requires. These
#' packages are loaded in the LaTeX preamble generated by [fr_render()] when
#' producing `.pdf` or `.tex` output.
#'
#' Most packages ship with a full TeX Live installation, but **tabularray** is
#' often missing from minimal distributions like tinytex. Use
#' [fr_install_latex_deps()] to install everything at once.
#'
#' @return A character vector of CTAN package names.
#'
#' @seealso [fr_install_latex_deps()] to install these packages,
#'   [fr_render()] for PDF output.
#'
#' @examples
#' fr_latex_deps()
#'
#' @export
fr_latex_deps <- function() {
  fr_env$required_latex_pkgs
}


#' Install Required LaTeX Packages
#'
#' Proactively installs all LaTeX packages needed by arframe's PDF backend
#' via [tinytex::tlmgr_install()]. Call this once after
#' `tinytex::install_tinytex()` to ensure [fr_render()] can produce PDFs
#' without interruption.
#'
#' @details
#' The [tinytex][tinytex::tinytex] package must be installed. If it is not,
#' `fr_install_latex_deps()` raises an error with installation instructions.
#'
#' Packages already present are silently skipped by `tlmgr`.
#'
#' @return Invisible `NULL`. Called for its side effect of installing packages.
#'
#' @seealso [fr_latex_deps()] for the package list,
#'   [fr_render()] for PDF output.
#'
#' @examples
#' if (requireNamespace("tinytex", quietly = TRUE) && tinytex::is_tinytex()) {
#'   fr_install_latex_deps()
#' }
#'
#' @export
fr_install_latex_deps <- function() {
  if (!requireNamespace("tinytex", quietly = TRUE)) {
    cli_abort(c(
      "Package {.pkg tinytex} is required to install LaTeX dependencies.",
      "i" = "Install via {.code install.packages(\"tinytex\")}.",
      "i" = "Then run {.code tinytex::install_tinytex()} to set up a TeX distribution."
    ), call = caller_env())
  }
  pkgs <- fr_env$required_latex_pkgs
  cli_inform(c("i" = "Installing {length(pkgs)} LaTeX package{?s} via tlmgr."))
  tinytex::tlmgr_install(pkgs)
  invisible(NULL)
}


# ── Internal compilation ─────────────────────────────────────────────────────

#' Render an fr_spec to PDF via XeLaTeX
#'
#' @param spec Finalized fr_spec object.
#' @param page_groups List of page group lists (data + group_label).
#' @param col_panels List of column name vectors (one per panel).
#' @param path Output file path (.pdf).
#' @noRd
render_pdf <- function(spec, page_groups, col_panels, path) {
  # 1. Write .tex to tempdir
  base_name <- file_path_sans_ext(basename(path))
  tex_dir <- tempdir()
  tex_path <- file.path(tex_dir, paste0(base_name, ".tex"))
  render_latex(spec, page_groups, col_panels, tex_path)

  # 2. Compile via shared helper
  compile_xelatex_doc(tex_path)

  # 3. Copy PDF to output path (skip if already in place)
  pdf_temp <- file.path(tex_dir, paste0(base_name, ".pdf"))
  if (
    normalizePath(pdf_temp, mustWork = FALSE) !=
      normalizePath(path, mustWork = FALSE)
  ) {
    file.copy(pdf_temp, path, overwrite = TRUE)
  }

  # 4. Cleanup temp files
  cleanup_latex_temps(tex_dir, base_name)

  invisible(path)
}


#' Compile a .tex file to PDF using XeLaTeX
#'
#' Shared compilation logic used by both `render_pdf()` (tables) and
#' `render_figure_pdf()` (figures). When tinytex is available, uses
#' `tinytex::xelatex()` which handles two-pass compilation AND auto-installs
#' missing LaTeX packages. Falls back to raw `system2()` with `find_xelatex()`
#' otherwise.
#'
#' @param tex_path Path to the .tex source file.
#' @return Invisible path to the compiled PDF.
#' @noRd
compile_xelatex_doc <- function(tex_path) {
  tex_dir <- dirname(tex_path)
  base_name <- file_path_sans_ext(basename(tex_path))

  # Set OSFONTDIR so XeLaTeX discovers fonts in ARFRAME_FONT_DIR

  font_dir <- get_font_dir()
  if (!is.null(font_dir)) {
    old_osfontdir <- Sys.getenv("OSFONTDIR", unset = NA)
    existing <- if (!is.na(old_osfontdir)) old_osfontdir else ""
    sep <- if (.Platform$OS.type == "windows") ";" else ":"
    new_val <- if (nzchar(existing)) {
      paste0(font_dir, sep, existing)
    } else {
      font_dir
    }
    Sys.setenv(OSFONTDIR = new_val)
    on.exit(
      {
        if (is.na(old_osfontdir)) {
          Sys.unsetenv("OSFONTDIR")
        } else {
          Sys.setenv(OSFONTDIR = old_osfontdir)
        }
      },
      add = TRUE
    )
  }

  if (requireNamespace("tinytex", quietly = TRUE)) {
    # tinytex::xelatex() handles two-pass compilation and auto-installs
    # missing packages via parse_install().
    # Set working directory to tempdir to prevent .log file leakage into
    # the user's working directory when tinytex retains logs on warnings.
    old_wd <- setwd(tex_dir)
    on.exit(setwd(old_wd), add = TRUE)
    tryCatch(
      tinytex::xelatex(tex_path),
      error = function(e) {
        log_file <- file.path(tex_dir, paste0(base_name, ".log"))
        report_latex_failure(log_file, tex_path, conditionMessage(e))
      }
    )
  } else {
    # Fallback: raw system2()
    xelatex <- find_xelatex()
    if (is.null(xelatex)) {
      cli_abort(c(
        "XeLaTeX not found on your system.",
        "i" = "Install {.pkg tinytex} for automatic LaTeX package management:",
        " " = "{.code install.packages(\"tinytex\")}",
        " " = "{.code tinytex::install_tinytex()}",
        " " = "{.code arframe::fr_install_latex_deps()}"
      ), call = caller_env())
    }

    args <- c(
      "-interaction=nonstopmode",
      "-output-directory",
      tex_dir,
      tex_path
    )
    system2(xelatex, args, stdout = TRUE, stderr = TRUE)
    system2(xelatex, args, stdout = TRUE, stderr = TRUE)

    # Check compilation succeeded
    pdf_path <- file.path(tex_dir, paste0(base_name, ".pdf"))
    if (!file.exists(pdf_path)) {
      log_file <- file.path(tex_dir, paste0(base_name, ".log"))
      report_latex_failure(log_file, tex_path)
    }
  }

  # Clean up auxiliary files (.log, .aux, .out, .fls, .fdb_latexmk)
  # tinytex::xelatex(clean = TRUE) handles this for the tinytex path;
  # this covers the system2 fallback and any leftover files.
  aux_exts <- c(".log", ".aux", ".out", ".fls", ".fdb_latexmk")
  aux_files <- file.path(tex_dir, paste0(base_name, aux_exts))
  unlink(aux_files[file.exists(aux_files)])

  invisible(file.path(tex_dir, paste0(base_name, ".pdf")))
}


#' Report LaTeX compilation failure with actionable diagnostics
#'
#' Parses the XeLaTeX log file for missing `.sty` files and produces a
#' targeted error message. For missing packages, suggests
#' `fr_install_latex_deps()`. For other errors, shows the log tail.
#'
#' @param log_file Path to the .log file.
#' @param tex_path Path to the .tex source (shown in error message).
#' @param original_msg Optional error message from tinytex (prepended).
#' @return Does not return; always aborts via [cli::cli_abort()].
#' @noRd
report_latex_failure <- function(
  log_file,
  tex_path,
  original_msg = NULL,
  call = caller_env()
) {
  if (!file.exists(log_file)) {
    cli_abort(
      c(
        original_msg %||% "XeLaTeX compilation failed.",
        "i" = "Source file: {.path {tex_path}}",
        "i" = "No log file found for diagnostics."
      ),
      call = call
    )
  }

  log_lines <- readLines(log_file, warn = FALSE)

  # Detect missing .sty files
  sty_pattern <- "! LaTeX Error: File `([^']+)\\.sty' not found"
  sty_matches <- regmatches(log_lines, regexec(sty_pattern, log_lines))
  missing_pkgs <- vapply(
    sty_matches,
    function(m) {
      if (length(m) >= 2L) m[[2L]] else NA_character_
    },
    character(1)
  )
  missing_pkgs <- unique(missing_pkgs[!is.na(missing_pkgs)])

  if (length(missing_pkgs) > 0L) {
    pkg_list <- paste0("{.pkg ", missing_pkgs, "}", collapse = ", ")
    cli_abort(
      c(
        original_msg %||%
          "XeLaTeX compilation failed due to missing LaTeX packages.",
        "x" = paste0("Missing: ", pkg_list),
        "i" = "Install with: {.code arframe::fr_install_latex_deps()}",
        "i" = "Or manually: {.code tinytex::tlmgr_install({deparse(missing_pkgs)})}"
      ),
      call = call
    )
  }

  # Generic failure: show log tail
  log_tail <- utils::tail(log_lines, 20L)
  safe_log <- gsub(
    "{",
    "{{",
    fixed = TRUE,
    gsub("}", "}}", log_tail, fixed = TRUE)
  )
  cli_abort(
    c(
      original_msg %||% "XeLaTeX compilation failed.",
      "i" = "Source file: {.path {tex_path}}",
      "i" = "Last 20 lines of log:",
      paste0("  ", safe_log)
    ),
    call = call
  )
}


#' Clean up LaTeX temporary files
#'
#' @param tex_dir Directory containing temp files.
#' @param base_name File base name (no extension).
#' @noRd
cleanup_latex_temps <- function(tex_dir, base_name) {
  exts <- c(".aux", ".log", ".out", ".toc")
  for (ext in exts) {
    unlink(file.path(tex_dir, paste0(base_name, ext)))
  }
}


#' Find xelatex binary
#'
#' Checks: (1) Sys.which, (2) tinytex if available.
#'
#' @return Path to xelatex binary, or NULL if not found.
#' @noRd
find_xelatex <- function() {
  # 1. System PATH
  path <- Sys.which("xelatex")
  if (nzchar(path)) {
    return(unname(path))
  }

  # 2. tinytex
  if (requireNamespace("tinytex", quietly = TRUE)) {
    path <- tryCatch(
      tinytex::tinytex_root(),
      error = function(e) NULL
    )
    if (!is.null(path)) {
      bin <- file.path(path, "bin", "*", "xelatex")
      candidates <- Sys.glob(bin)
      if (length(candidates) > 0L) {
        return(candidates[1L])
      }

      # Windows: .exe
      bin_exe <- file.path(path, "bin", "*", "xelatex.exe")
      candidates <- Sys.glob(bin_exe)
      if (length(candidates) > 0L) return(candidates[1L])
    }
  }

  NULL
}
